{"artifact": "showcase/case1/map_icon@480.png", "exception": "RuntimeError: Could not locate imagemagick.", "traceback": "Traceback (most recent call last):\n  File \"d:\\\u500b\u4eba\u8cc7\u6599\\desktop\\\u6f6a\u69a4\\python\\mylektor\\venv\\lib\\site-packages\\lektor\\builder.py\", line 800, in update\n    yield ctx\n  File \"d:\\\u500b\u4eba\u8cc7\u6599\\desktop\\\u6f6a\u69a4\\python\\mylektor\\venv\\lib\\site-packages\\lektor\\builder.py\", line 1070, in build_artifact\n    build_func(artifact)\n  File \"d:\\\u500b\u4eba\u8cc7\u6599\\desktop\\\u6f6a\u69a4\\python\\mylektor\\venv\\lib\\site-packages\\lektor\\imagetools.py\", line 483, in build_thumbnail_artifact\n    width, height, crop=crop, quality=quality)\n  File \"d:\\\u500b\u4eba\u8cc7\u6599\\desktop\\\u6f6a\u69a4\\python\\mylektor\\venv\\lib\\site-packages\\lektor\\imagetools.py\", line 429, in process_image\n    ctx.build_state.config['IMAGEMAGICK_EXECUTABLE'])\n  File \"d:\\\u500b\u4eba\u8cc7\u6599\\desktop\\\u6f6a\u69a4\\python\\mylektor\\venv\\lib\\site-packages\\lektor\\imagetools.py\", line 384, in find_imagemagick\n    raise RuntimeError('Could not locate imagemagick.')\nRuntimeError: Could not locate imagemagick."}
